name = "SteinDiscrepancy"
uuid = "47571ba0-6b7d-4e5f-b5d0-9456c75a042d"
keywords = ["statistics"]
license = "MIT"
desc = "Practical tools for quantifying how well a sample approximates a target distribution."
version = "1.5.0"

[deps]
BinDeps = "9e28174c-4ba2-5203-b857-d8d62c4213ee"
Clp = "e2554f3b-3117-50c0-817c-e040a3ddf72d"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
MathProgBase = "fdba3010-5040-5b88-9595-932c9decdf73"
